---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Print hello world
      ansible.builtin.debug:
        msg: "Hola ke ase"
    - name: Ping host
      ansible.builtin.ping:
      register: ping_result
    # Este es un comentario
    - name: Print ping result
      ansible.builtin.debug:
        msg: "{{ ping_result }}"
