# prerequisites:
#   ansible-galaxy collection install community.docker
---
- hosts: all
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name:
          - docker
        state: latest
    - name: enable and start docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
    - name: run dockerized application
      community.docker.docker_container:
        name: vue2048
        image: javierrgz/vue-2048
        published_ports: '80:80'
