# run:
#   ansible-playbook -i all.aws_ec2.yml setup-instances.yml
---
- hosts: all
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name:
          - nginx
        state: latest
    - name: start service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: deploy webpage
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/
